name: Leak Sanitizer

on:
  push:
    branches:
    - DemoApp
    paths-ignore:
    - 'cmake/**'
    - '.github/**'
    - 'doc/**'
    - 'samples/**'

jobs:
  Leak_Sanitizer:
    strategy:
      matrix:
        fs: [DIRENT, STD]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: DemoApp
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : sudo apt-get update && sudo apt-get install libgl1-mesa-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev
    - name: configure
      run: >
        mkdir build && cd build && cmake .. 
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_BUILD_TYPE=Release 
        -DUSE_TEST=ON 
        -DUSE_LEAK_SANITIZER=ON
        -DUSE_${{ matrix.fs }}_FILESYSTEM=ON
    - name: build
      run: cmake --build build --config Release
    - name: ctest
      run: ctest --test-dir build --output-on-failure
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ImGuiFileDialog_App_Unix_${{ matrix.fs }}_FS
        path: bin/ImGuiFileDialog_App_Unix
