name: Linux

on:
  push:
    branches:
    - DemoApp

jobs:
  build_Linux_Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: DemoApp
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : sudo apt-get update && sudo apt-get install libgl1-mesa-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_TEST=ON
    - name: build DemoApp
      run: cmake --build build --config Release -t ImGuiFileDialog_App
    - name: CTest build test app
      run: cmake --build build --config Release -t ImGuiFileDialog_Test
    - name: CTest
      run: ctest --test-dir build --output-on-failure
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ImGuiFileDialog
        path: build/ImGuiFileDialog
      
