name: Osx

on:
  push:
    branches:
    - master

jobs:
  build_Osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : brew update
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ImGuiFileDialog.app
        path: build/ImGuiFileDialog.app
