name: Win Msvc

on:
  push:
    branches:
    - DemoApp
    paths-ignore:
    - 'cmake/**'
    - '.github/**'
    - 'doc/**'
    - 'samples/**'

jobs:
  Win_Msvc:
    strategy:
      matrix:
        fs: [DIRENT, STD]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: DemoApp
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: configure
      run: >
        mkdir build && cd build && cmake .. 
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release 
        -DUSE_TEST=ON 
        -DUSE_${{ matrix.fs }}_FILESYSTEM=ON
    - name: build
      run: cmake --build build --config Release
    - name: ctest
      run: ctest --test-dir build --output-on-failure
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ImGuiFileDialog_App_Win32_${{ matrix.fs }}_FS
        path: bin\ImGuiFileDialog_App_Win32.exe
